let MCQS = [{
    question: "What does P2P stand for?",
    choice1: "Peer to Peer ",
    choice2: "Product to Product ",
    choice3: "Password to Password",
    choice4: "Private Key to Public Key ",
    answer: "1",
},
{
    question: "What is a smart contract?",
    choice1: "Online contract",
    choice2: "Offline contract ",
    choice3: "Digital contract ",
    choice4: "Programs stored on a blockchain that run when predetermined conditions are met  ",
    answer: "4",
},
{
    question: "Where is a Blockchains central server?",
    choice1: "Ordered Node ",
    choice2: "Where the blockchain is created",
    choice3: "There is no central server, it is distributed ",
    choice4: "Located with the owner of the server ",
    answer: "3",
},
{
    question: "The height of the block is the ____ in the chain between it and the genesis block.",
    choice1: "Metadata that is",
    choice2: "Merkle tree hash ",
    choice3: "Size of the memory cache ",
    choice4: "Number of blocks ",
    answer: "4",
},
{
    question: "What is not a ledger type considered by users in Blockchain?",
    choice1: " Distributed Ledger",
    choice2: " Decentralized Ledger",
    choice3: "Both (A) and (B)",
    choice4: "None of the Above",
    answer: "4",
},
{
    question: "How does blockchain technology help organizations when sharing data?",
    choice1: "Data can only be exchanged through a central, trusted organization.",
    choice2: "Data can be edited or removed only through certain authorized central nodes.",
    choice3: "Everyone has transparency over how the data has been added.",
    choice4: "Data can only be exchanged through a central, trust organization",
    answer: "4",
},
{
    question: ".What is Hyperledger Fabric?",
    choice1: "A cryptocurrency",
    choice2: "A blockchain platform for building decentralized applications ",
    choice3: "A distributed ledger technology for tracking supply chains ",
    choice4: "A smart contract platform for executing automated transactions ",
    answer: "2",
}, {
    question: " What is a hash pointer?",
    choice1: " A pointer to a memory location in a computer's RAM",
    choice2: "A pointer to a block in a blockchain ",
    choice3: "A pointer to a block in a blockchain ",
    choice4: "A pointer that includes the timestamp of the data it points to",
    answer: "3",
},
{
    question: "What is the core domain for Accenture’s Multi-party Systems practice?",
    choice1: ".social networking ",
    choice2: " .social networking",
    choice3: " .digital identity",
    choice4: ".employee retention",
    answer: "3",
},
{
    question: " What is one of the reasons to consider implementing a blockchain solution?",
    choice1: "ability to work on different versions of the same data",
    choice1: "inability to trace and access data of other users",
    choice1: "ability to verify that data has not been tampered with since its creation",
    choice1: ".inability to track simultaneous updates by multiple users",
    answer: "3",
}];