let MCQS = [{
    question: "What is Cloud Computing?",
    choice1: "Cloud Computing means providing services like storage, servers, database, networking, etc",
    choice2: "Cloud Computing means storing data in a database",
    choice3: "Cloud Computing is a tool used to create an application",
    choice4: "All of the mentioned",
    answer: "1",
},
{
    question: "Which of the following architectural standards is working with cloud computing industry?",
    choice1: "Web-application frameworks ",
    choice2: "Service-oriented architecture ",
    choice3: "Standardized Web services ",
    choice4: "None of the above ",
    answer: "2",
},
{
    question: " All cloud computing applications suffer from the inherent _______ that is intrinsic in their WAN connectivity.",
    choice1: " noise ",
    choice2: "propagation ",
    choice3: "latency ",
    choice4: "all of the mentioned",
    answer: "3",
},
{
    question: "Which of the following is not a type of cloud server?",
    choice1: "Public Cloud Servers ",
    choice1: " Private Cloud Servers ",
    choice1: " Dedicated Cloud Servers ",
    choice1: "Merged Cloud Servers ",
    answer: "4",
},
{
    question: " Which of the following is the application of cloud computing?",
    choice1: "Adobe ",
    choice2: "Paypal ",
    choice3: "Google G Suite ",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "Which architectural layer is used as a backend in cloud computing?",
    choice1: "cloud ",
    choice2: "soft ",
    choice3: "client",
    choice4: "all of the mentioned ",
    answer: "1",
},
{
    question: "Which of the following is the Cloud Platform provided by Amazon?",
    choice1: "AWS",
    choice2: "Cloudera ",
    choice3: "Azure ",
    choice4: "All of the mentioned  ",
    answer: "1",
}, {
    question: "Which of the following model consists of the service that you can access on a cloud computing platform?",
    choice1: "Deployment  ",
    choice1: "Service ",
    choice1: "Application ",
    choice1: "None of the mentioned ",
        answer: "2",
},
{
    question: "In which of the following service models the hardware is virtualized in the cloud?.",
    choice1: "NaaS",
    choice2: "PaaS ",
    choice3: "CaaS ",
    choice4: "IaaS ",
        answer: "4",
},
{
    question: "Which one of the following refers to the non-functional requirements like disaster recovery, security, reliability, etc.",
    choice1: "Service Development ",
    choice2: "Quality of service ",
    choice3: "Plan Development",
    choice4: "Technical Service ",
    answer: "2",
}];