let MCQS = [{
    question: "Find the value of ∫∫xyex + y dxdy.",
    choice1: "ye^y (xe^x-e^x)",
    choice2: "(ye^y-e^y)(xe^x-e^x)",
    choice3: "(ye^y-e^y)xe^x",
    choice4: " (ye^y-e^y)(xe^x+e^x)",
    answer: "2",
},
{
    question: "f(x, y) = x3 + xy2 + 901 satisfies the Eulers theorem.",
    choice1: "True",
    choice2: "False",
    
    answer: "2",
},
{
    question: "A non-polynomial function can never agree with eulers theorem.",
    choice1: "True",
    choice2: "False",
    answer: "2",
},
{
    question: "For a homogeneous function if critical points exist the value at critical points is?",
    choice1: "1",
    choice2: "equal to ts degree",
    choice3: "0",
    choice4: "-1",
    answer: "3",
},
{
    question: "f(x, y) = sin(y/x)x^3 + x^2y find the value of fx + fy at (x,y)=(4,4).",
    choice1: "0",
    choice2: "78",
    choice3: "4^2 /3(sin(1)+1)",
    choice4: "-12",
    answer: "3",
},
{
    question: "If f(t) = 1, then its Laplace Transform is given by?",
    choice1: "s",
    choice2: "1/s",
    choice3: "1",
    choice4: "Does not exist",
    answer: "2",
},
{
    question: "If f(t)=√t, then its Laplace Transform is given by?",
    choice1: "1/2",
    choice2: "1/s",
    choice3: "√π / 2√s",
    choice4: "Does not exist",
    answer: "3",
}, {
    question: " If f(t) = sin(at), then its Laplace Transform is given by?",
    choice1: " cos(at)",
    choice2: " 1 / a^sin(at)",
    choice3: "Indeterminate",
    choice4: " a  / s^2+a^2",
    answer: "4",
},
{
    question: " Evaluate the differentiation of tan^{-1}\frac{cos(x)-sin(x)}{cos(x)+sin(x)}",
    choice1: "tan^-1 (⁡x)",
    choice2: "1", 
    choice3: "0",
    choice4: "-1",
    answer: "2",
},
{
    question: "Evaluate d/dx Cot(x)Cosec(x)",
    choice1: "-Cosec^2 (x) - Cosec^2 (x)Cot(x)",
    choice2: "-Cosec^3 (x) - Cosec^2 (x)Cot(x)",
    choice3: " -Cosec(x) - Cosec^2 (x)Cot(x)",
    choice4: " -Cosec^3 (x) - Cosec(x)Cot^2 (x)",
    answer: "2",
}];