let MCQS = [{
    question: "________ is primarily a personal activty , mostly done as an individual",
    choice1: "Software engineering ",
    choice2: "Programming ",
    choice3: "Testing ",
    choice4: "Softeare development  ",
    answer: "1",
},
{
    question: "The role of SOftware and COmputer Programmer is _______",
    choice1: "Changeble  ",
    choice2: "Not changeble ",
    choice3: "Interchangeable ",
    choice4: "Not interchangeable ",
    answer: "4",
},
{
    question: "Tracking ________ helps you develop a holistic view of a development process",
    choice1: "Productivity ",
    choice2: "measuring ",
    choice3: "efficiency ",
    choice4: "scale ",
    answer: "c",
},
{
    question: "______ is used to help organization in effectively determining cause of problems that occurred.",
    choice1: "program ",
    choice2: "data ",
    choice3: "software ",
    choice4: "development ",
    answer: "2",
},
{
    question: "________ are used to speed up input and output processes in machine",
    choice1: "Programs ",
    choice2: "data ",
    choice3: "software ",
    choice4: "Development ",
    answer: "1",
},
{
    question: "Software is defined as ___________",
    choice1: "set of programs, documentation & configuration of data",
    choice2: "set of programs",
    choice3: "documentation and configuration of data",
    choice4: "None of the mentioned",
    answer: "1",
},
{
    question: "What is Software Engineering?",
    choice1: "Designing a software ",
    choice2: "Testing a software ",
    choice3: "Application of engineering principles to the design a software ",
    choice4: "None of the above ",
    answer: "3",
}, {
    question: "Who is the father of Software Engineering?",
    choice1: "Margaret Hamilton ",
    choice2: "Watts S. Humphrey ",
    choice3: "Alan Turing ",
    choice4: "Boris Beizer ",
    answer: "2",
},
{
    question: "What are the features of Software Code?",
    choice1: "Simplicity ",
    choice2: "Accessibility ",
    choice3: "Modularity ",
    choice4: "All of the above ",
    answer: "3",
},
{
    question: " ____________ is a software development activity that is not a part of software processes.",
    choice1: "Validation ",
    choice2: "Specification ",
    choice3: "Development ",
    choice4: "Dependence ",
    answer: "4",
}];