let MCQS = [{
    question: "What does top down process follow?",
    choice1: "The overall flow of activity during product design resolution is from higher to lower levels",
    choice2: "The overall flow of activity during product design resolution is from lower to higher levels",
    choice3: "All of the mentioned",
    choice4: "None of the mentioned",
    answer: "1",
},
{
    question: "What are the most common scenarios for resolutions?",
    choice1: "Designers frequently work bottom up or skip levels of abstraction",
    choice2: "To specify some part of product design to its physical level details before others are specified",
    choice3: "All of the mentioned",
    choice4: "None of the mentioned",
    answer: "3",
},
{
    question: "Lower level of abstraction includes?",
    choice1: "Product features",
    choice2: "Functions",
    choice3: "Properties",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "Product design is mainly?",
    choice1: "Top-down approach",
    choice2: "Bottom-up approach",
    choice3: "Top-down & Bottom-up approach",
    choice4: "None of the mentioned",
    answer: "1",
},
{
    question: "The user-centered design comprises of which of these principles?",
    choice1: "Stakeholder focus",
    choice2: "Empirical Evaluation",
    choice3: "Iteration",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "Collection of stakeholder needs is called?",
    choice1: "Requirements elicitation",
    choice2: "Requirements validation",
    choice3: "Needs Elicitation",
    choice4: "Requirements & Needs elicitation",
    answer: "4",
},
{
    question: "Understanding Stakeholder needs are called?",
    choice1: "Needs analysis",
    choice2: "Needs elicitation",
    choice3: "Needs identification",
    choice4: "All of the mentioned",
    answer: "1",
}, {
    question: "Confirming with stakeholder that a product design satisfies their needs and desires are called?",
    choice1: "Requirements validation",
    choice2: "Requirements elicitation",
    choice3: "Requirements analysis",
    choice4: "None of the mentioned",
    answer: "1",
},
{
    question: "Stakeholder role in analyzing needs?",
    choice1: "Answer questions",
    choice2: "Clarify project mission statement",
    choice3: "Review and validate models and documents",
    choice4: " Answer questions, Review and validate models and documents",
    answer: "4",
},
{
    question: "Stakeholder role for Generate/Improve alternatives?",
    choice1: "Participate in generation and improvement",
    choice2: "Answer the question",
    choice3: "Be subject of empirical studies",
    choice4: "All of the mentioned",
    answer: "1",
}];