let MCQS = [{
    question: "If x is a set and the set contains an integer which is neither positive nor negative then the set x is ____________.",
    choice1: "Set is Empty",
    choice2: "Set is Non-empty",
    choice3: "Set is Finite.",
    choice4: "Set is both Non- empty and Finite.",
    answer: "4",
},
{
    question: "If x ∈ N and x is prime, then x is ________ set.",
    choice1: "Infinite set",
    choice2: "Finite set",
    choice3: "Empty set",
    choice4: "Not a set",
    answer: "1",
},
{
    question: "If x is a set and the set contains the real number between 1 and 2, then the set is ________.",
    choice1: "Empty set",
    choice2: "Finite set",
    choice3: "Infinite set",
    choice4: "None of the mentioned",
    answer: "3",
},
{
    question: "Which of the following is a subset of set {1, 2, 3, 4}?",
    choice1: "{1, 2}",
    choice2: "{1, 2, 3}",
    choice3: "{1}",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "Power set of empty or Null set has exactly _________ subset",
    choice1: "One",
    choice2: "Two",
    choice3: "zero",
    choice4: "three",
    answer: "1",
},
{
    question: "If n(A) = 20 and n(B) = 30 and n(A U B) = 40 then n(A ∩ B) is?",
    choice1: "20",
    choice2: "30",
    choice3: "40",
    choice4: "10",
    answer: "4",
},
{
    question: "Which among the following can be taken as the discrete object?",
    choice1: "People",
    choice2: "Rational Numbers",
    choice3: "Integer",
    choice4: "All of the mentioned",
    answer: "4",
}, {
    question: "The cardinality of the Power set of the set {1, 5, 6} is______________.",
    choice1: "5",
    choice2: "6",
    choice3: "8",
    choice4: "10",
    answer: "3",
},
{
    question: "Mathematics can be broadly categorized into how many types?",
    choice1: "3 types",
    choice2: "2 types",
    choice3: "5 types",
    choice4: "4 types",
    answer: "2",
},
{
    question: "Which of the following function is also referred to as an injective function?",
    choice1: "Many to one",
    choice2: "Onto",
    choice3: "One to one",
    choice4: "None of mentioned",
    answer: "3",
}];