let MCQS = [{
    question: "Which among the following is considered to be the main determinant of the level of activity is in national income terms?",
    choice1: "The level of taxation",
    choice2: "Realized investment",
    choice3: "Planned saving",
    choice4: "Factor mobility",
    answer: "2",
},
{
    question: "Which among the following imposes a greater burden (relative to resources) on the poor than on the rich ?",
    choice1: "Progressive tax",
    choice2: "Regressive Tax",
    choice3: "Lump Sum tax",
    choice4: "Proportional tax",
    answer: "2",
},
{
    question: "Which among the following phrases generally denotes National Income?",
    choice1: "Gross National Product at Market Prices",
    choice2: "Net National Product at Market Prices",
    choice3: "Gross National Product at Factor Cost",
    choice4: "Net National Product at Factor Cost",
    answer: "4",
},
{
    question: "A monopolist will be able to maximize his profits when _________?",
    choice1: "His output is maximum",
    choice2: "He charges a Higher price",
    choice3: "His average cost is minimum",
    choice4: "His marginal cost is equal to the marginal revenue",
    answer: "4",
},
{
    question: "Which one of the following is NOT a sign of economic development?",
    choice1: "Changing structure of GDP in favour of industry",
    choice2: "Larger share of GDP coming from primary sector",
    choice3: "Larger capital inflows",
    choice4: "Institutional changes in an economy.",
    answer: "3",
},
{
    question: "Which of the following is not added in the calculation of national income of India?",
    choice1: "The value of goods and services",
    choice2: "The sold value of the old fridge",
    choice3: "Services rendered by the housewives",
    choice4: "Both b & c",
    answer: "4",
},
{
    question: "In which of the following market forms a firm does not exercise control over price?",
    choice1: "Monopoly",
    choice2: "Mixed Competition",
    choice3: "Perfect competition",
    choice4: "Oligopoly",
    answer: "3",
}, {
    question: "Which of the following is an alternative way of representing the production function?",
    choice1: "Average Product",
    choice2: "The Long Run",
    choice3: "Isoquant",
    choice4: "The Short Run",
    answer: "3",
},
{
    question: "A transfer payment is a payment that is __:",
    choice1: "made by the government to its current workers",
    choice2: "made to people who are needy",
    choice3: "For in-kind services provided to the government",
    choice4: "For which no services or goods are rendered",
    answer: "4",
},
{
    question: "Which of the following is the movement along the supply curve?",
    choice1: "Curve Supply",
    choice2: "Contraction of supply",
    choice3: "Expansion of supply",
    choice4: "Expansion and contraction of supply",
    answer: "4",
}];