let MCQS = [{
    question: "What is Artificial Intelligence?",
    choice1: "Artificial Intelligence is a field that aims to make humans more intelligent",
    choice2: "Artificial Intelligence is a field that aims to improve the security",
    choice3: "Artificial Intelligence is a field that aims to develop intelligent machines",
    choice4: "Artificial Intelligence is a field that aims to mine the data",
    answer: "3",
},
{
    question: " Who is the inventor of Artificial Intelligence?",
    choice1: "Geoffrey Hinton",
    choice2: "Andrew Ng",
    choice3: "John McCarthy",
    choice4: "Jürgen Schmidhuber",
    answer: "3",
},
{
    question: "Which of the following is the branch of Artificial Intelligence?",
    choice1:  "Machine Learning",
    choice2: "Cyber forensics",
    choice3: "Full-Stack Developer",
    choice4: "Network Design",
    answer: "1",
},
{
    question: "What is the goal of Artificial Intelligence?",
    choice1: "To solve artificial problems",
    choice2: "To extract scientific causes",
    choice3: "To explain various sorts of intelligence",
    choice4: "To solve real-world problems",
    answer: "3",
},
{
    question: "Which of the following is a component of Artificial Intelligence?",
    choice1: "Learning",
    choice2: "training",
    choice3: "Designing",
    choice4: "Puzzling",
    answer: "1",
},
{
    question: "What is the function of an Artificial Intelligence “Agent”?",
    choice1: "Mapping of goal sequence to an action",
    choice2: "Work without the direct interference of the people",
    choice3: "Mapping of precept sequence to an action",
    choice4: "Mapping of environment sequence to an action",
    answer: "3",
},
{
    question: "Which of the following is not a type of Artificial Intelligence agent?",
    choice1: "Learning AI agent",
    choice2: "Goal-based AI agent",
    choice3: "Simple reflex AI agent",
    choice4: "Unity-based AI agent",
    answer: "4",
}, {
    question: "Which of the following is not the commonly used programming language for Artificial Intelligence?",
    choice1: "perl",
    choice2: "java",
    choice3: "PROLOG",
    choice4: "LISP",
    answer: "1",
},
{
    question: "What is the function of the system Student?",
    choice1: "program that can read algebra word problems only",
    choice2: "system which can solve algebra word problems but not read",
    choice3: "system which can read and solve algebra word problems",
    choice4: "None of the mentioned",
    answer: "3",
},
{
    question: "Which of the following is not an application of artificial intelligence?",
    choice1: "Face recognition system ",
    choice2: "Chatbots",
    choice3: "LIDAR",
    choice4: "DBMS",
    answer: "4",
}];