
let MCQS = [{
    question: "Hardness of water is due to the presence of salts of ",
    choice1: "potassium",
    choice2: "chlorine",
    choice3: "magnesium",
    choice4: "boron",
    answer: "3",
},
{
    question: "Select the incorrect statement from the following option.",
    choice1: "water which does not form lather with soap and forms white scum is called hard water",
    choice2: "hard water contains dissolved calcium and magnesium salts in it",
    choice3: "in hard water, cleansing quality of soap is depressed",
    choice4: "due to the presence of dissolved hardness- producing salts, the boiling point of water is depressed",
    answer: "4",
},
{
    question: "Which of the following is not a unit of hardness?",
    choice1: "parts per million",
    choice2: "degree centigrade",
    choice3: "degree clarke",
    choice4: "degree french",
    answer: "2",
},
{
    question: "The chemical equivalent of MgSO4 salt is",
    choice1: "10000",
    choice2: "30000",
    choice3: "50000",
    choice4: "70000",
    answer: "4",
},
{
    question: "1 ppm =",
    choice1: "0.07 0fr",
    choice2: "0.70fr",
    choice3: "0.10fr",
    choice4: "0.010fr",
    answer: "3",
},
{
    question: "How many grams of MgCO3 dissolved per litre gives 84 ppm hardness?",
    choice1: "70.56 mg/l",
    choice2: "48.23 mg/l",
    choice3: "81.49mg/l",
    choice4: "66.12 mg/l",
    answer: "1",
},
{
    question: "Estimation of hardness can be determined by ",
    choice1: "2",
    choice2: "3",
    choice3: "4",
    choice4: "5",
    answer: "1",
}, {
    question: "The sodium soap will precipitate all the hardness causing ions into their respective",
    choice1: "carbonates",
    choice2: "bicarbonates",
    choice3: "stereates",
    choice4: "chlorides",
    answer: "3",
},
{
    question: "The water which form lather directly with the soap is called",
    choice1: "hard water",
    choice2: "soft water",
    choice3: "partially hard water",
    choice4: "very hard water",
    answer: "2",
},
{
    question: "The indicator used in the EDTA method is",
    choice1: "benzene",
    choice2: "phenopthalene",
    choice3: "ethylene diamine",
    choice4: "erichrome black t",
    answer: "4",
}];