let MCQS = [{
    question: "Numerical techniques more commonly involve _______",
    choice1: "Elimination method",
    choice2: "Reduction method",
    choice3: "Iterative method",
    choice4: "Direct method",
    answer: "3",
},
{
    question: "Which of the following is an iterative method?",
    choice1: "Gauss Seidel",
    choice2: "Gauss Jordan",
    choice3: "Factorization",
    choice4: "Gauss Elimination",
    answer: "2",
},
{
    question: "Which of the following is also known as the Newton Raphson method?",
    choice1: "Chord method",
    choice2: "Tangent method",
    choice3: "Diameter method",
    choice4: "Secant method",
    answer: "2",
},
{
    question: "Which of the methods is a direct method for solving simultaneous algebraic equations?",
    choice1: "Relaxation method",
    choice2: "Gauss seidel method",
    choice3: "Jacobi’s method",
    choice4: "Cramer’s rule",
    answer: "4",
},
{
    question: "Which of the following is the advantage of using the Gauss Jordan method?",
    choice1: "Additional Calculations",
    choice2: "No labour of back substitution",
    choice3: "More operations involved",
    choice4: "Elimination is easier",
    answer: "2",
},
{
    question: "Matrix which does not have an inverse by solving it, is classified as which of the following?",
    choice1: "singular matrix",
    choice2: "non-singular matrix",
    choice3: "linear matrix",
    choice4: "unidentified matrix",
    answer: "1",
},
{
    question: "Which of the following transformations are allowed in the Gauss Jordan method?",
    choice1: "Swapping a column",
    choice2: "Swapping two rows",
    choice3: "Swapping two columns",
    choice4: "Swapping a row",
    answer: "2",
}, {
    question: "The Gauss Jordan method reduces a original matrix into a",
    choice1: "Skew Hermitian matrix",
    choice2: "Non-symmetric matrix",
    choice3: "Identity matrix",
    choice4: "Null matrix",
    answer: "3",
},
{
    question: "What is the other name for factorization method?",
    choice1: "Muller’s Method",
    choice2: "Decomposition Method",
    choice3: "Lin Bairstow Method",
    choice4: "Doolittle’s Method",
    answer: "4",
},
{
    question: "Cramer’s Rule fails for ___________",
    choice1: "Determinant = 0",
    choice2: "Determinant = non-real",
    choice3: "Determinant < 0",
    choice4: "Determinant > 0",
    answer: "1",
}];