let MCQS = [{
    question: "Agile is an __________ of software development methodology",
    choice1: "linear approaches",
    choice2: "incremental approach",
    choice3: "iterative approach",
    choice4: "simple approch",
    answer: "3",
},
{
    question: "Which of the following are correct quality strategies of agile?",
    choice1: "Short feedback cycles",
    choice2: "Milestone reviews",
    choice3: "Dynamic code analysis",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "Agile has ________ manifesto.",
    choice1: "2",
    choice2: "3",
    choice3: "4",
    choice4: "5 ",
    answer: "3",
},
{
    question: "Which of the following are disadvantage of the agile model?",
    choice1: "The development team should be highly professional and client-oriented.",
    choice2: " New requirement may be a conflict with the existing architecture",
    choice3: "There may be difficult to estimate the final coast of the project due to constant iteration",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "Which chart depicts the amount of work done in the project?",
    choice1: "burn-down",
    choice2: "burn-up",
    choice3: "Both A and B",
    choice4: "None of the above",
    answer: "2",
},
{
    question: "Which on of the following is not an agile method?",
    choice1: "XP",
    choice2: "4GT",
    choice3: "AUP",
    choice4: "none of the above",
    answer: "2",
},
{
    question: "Social, economical and ecological equity is the necessary condition for achieving",
    choice1: "Social development",
    choice2: "Economical development",
    choice3: "Sustainable development",
    choice4: "Ecological development",
    answer: "3",
}, {
    question: "The maximum number of individuals that can be supported by a given environment is called",
    choice1: "Biotic potential",
    choice2: "Carrying capacity",
    choice3: "Environmental resistance",
    choice4: "Population size",
    answer: "2",
},
{
    question: "What is gini index?",
    choice1: "operates on the categorical target variables",
    choice2: "it is a measure of purity",
    choice3: "gini index performs only binary split",
    choice4: "all (1,2 and 3)",
    answer: "4",
},
{
    question: "System Testing is a ______",
    choice1: "Black box testing",
    choice2: "White box testing",
    choice3: "Grey box testing",
    choice4: "Both a and b ",
    answer: "1",
}];