let MCQS = [{
    question: " ML is a field of AI consisting of learning algorithms that?",
    choice1: "Improve their performance",
    choice2: "At executing some task",
    choice3: "Over time with experience",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "p → 0q is not a?",
    choice1: "hack clause",
    choice2: "horn clause",
    choice3: "structural clause",
    choice4: "system clause",
    answer: "2",
},
{
    question: "The action _______ of a robot arm specify to Place block A on block B.",
    choice1: "STACK(A,B)",
    choice2: "LIST(A,B)",
    choice3: "QUEUE(A,B)",
    choice4: "ARRAY(A,B)",
    answer: "1",
},
{
    question: "A model of language consists of the categories which does not include ________",
    choice1: "System Unit",
    choice2: "structural units.",
    choice3: "data units",
    choice4: "empirical units",
    answer: "2",
},
{
    question: "Different learning methods does not include?",
    choice1: "Introduction",
    choice2: "Analogy",
    choice3: "Deduction",
    choice4: "Memorization",
    answer: "1",
},
{
    question: "The model will be trained with data in one single batch is known as ?",
    choice1: "Batch learning",
    choice2: "Offline learning",
    choice3: "Both A and B",
    choice4: "None of the above",
    answer: "3",
},
{
    question: "Which of the following are ML methods?",
    choice1: "based on human supervision",
    choice2: "supervised Learning",
    choice3: "semi-reinforcement Learning",
    choice4: "All of the above",
    answer: "1",
}, {
    question: "Which of the following is a widely used and effective machine learning algorithm based on the idea of bagging?",
    choice1: "Decision Tree",
    choice2: "Regression",
    choice3: "Classification",
    choice4: "Random Forest",
    answer: "4",
},
{
    question: "To find the minimum or the maximum of a function, we set the gradient to zero because:",
    choice1: "The value of the gradient at extrema of a function is always zero",
    choice2: "Depends on the type of problem",
    choice3: "Both A and B",
    choice4: "None of the above",
    answer: "1",
},
{
    question: "Which of the following is a disadvantage of decision trees?",
    choice1: " Factor analysis",
    choice2: "Decision trees are robust to outliers",
    choice3: "Decision trees are prone to be overfit",
    choice4: "None of the above",
    answer: "3",
}];