let MCQS = [{
    question: "What is computer organization?",
    choice1: "structure and behaviour of a computer system as observed by the user",
    choice2: "structure of a computer system as observed by the developer",
    choice3: "structure and behaviour of a computer system as observed by the developer",
    choice4: "All of the mentioned",
    answer: "1",
},
{
    question: "Which of the following is a type of computer architecture?",
    choice1: "Microarchitecture",
    choice2: "Harvard Architecture",
    choice3: "Von-Neumann Architecture",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: " Which of the following is a type of architecture used in the computers nowadays?",
    choice1: "Microarchitecture",
    choice2: "Harvard Architecture",
    choice3: "Von-Neumann Architecture",
    choice4: "System Design",
    answer: "3",
},
{
    question: "Which of the architecture is power efficient?",
    choice1: "RISC",
    choice2: "ISA",
    choice3: "IANA",
    choice4: "CISC",
    answer: "1",
},
{
    question: "What does CSA stands for?",
    choice1: "Computer Service Architecture",
    choice2: "Computer Speed Addition",
    choice3: "Carry Save Addition",
    choice4: "None of the mentioned",
    answer: "2",
},
{
    question: " If an exception is raised and the succeeding instructions are executed completely, then the processor is said to have ______",
    choice1: "Generation word",
    choice2: "Exception handling",
    choice3: "Imprecise exceptions",
    choice4: "None of the mentioned",
    answer: "3",
},
{
    question: "To reduce the memory access time we generally make use of ______",
    choice1: "SDRAM’s",
    choice2: "Heaps",
    choice3: "Cache’s",
    choice4: "Higher capacity RAM’s",
    answer: "3",
}, {
    question: "The IA-32 system follows which of the following design?",
    choice1: "CISC",
    choice2: "SIMD",
    choice3: "RISC",
    choice4: "none of the mentioned",
    answer: "1",
},
{
    question: "The VLIW architecture follows _____ approach to achieve parallelism.",
    choice1: "SISD",
    choice2: "MIMD",
    choice3: "MISD",
    choice4: "SIMD",
    answer: "2",
},
{
    question: "Both the CISC and RISC architectures have been developed to reduce the ______",
    choice1: "Time delay",
    choice2: "Semantic gap",
    choice3: "Cost",
    choice4: "All of the mentioned",
    answer: "2",
}];