let MCQS = [{
    question: "In symmetric-key cryptography, the key locks and unlocks the box is",
    choice1: "same",
    choice2: "shared",
    choice3: "private",
    choice4: "public",
    answer: "1",
},
{
    question: "The keys used in cryptography are",
    choice1: "secret key",
    choice2: "private key",
    choice3: "public key",
    choice4: "all of them",
    answer: "4",
},
{
    question: "Cryptography, a word with Greek origins, means",
    choice1: "corrupting data",
    choice2: "secret writing",
    choice3: "open writing",
    choice4: "closed writing",
    answer: "2",
},
{
    question: "A transposition cipher reorders (permutes) symbols in a",
    choice1: "block of packets",
    choice2: "block of slots",
    choice3: "block of signals",
    choice4: "block of symbols",
    answer: "4",
},
{
    question: "Network Security provides authentication and access control for resources.",
    choice1: "True",
    choice2: "False",
    
    answer: "1",
},
{
    question: "Which is not an objective of network security?",
    choice1: "identification",
    choice2: "authentication",
    choice3: "access control ",
    choice4: "lock",
    answer: "4",
},
{
    question: "The process of transforming plain text into unreadable text.",
    choice1: "decryption",
    choice2: "encryption",
    choice3: "network security",
    choice4: "information hiding",
    answer: "2",
}, {
    question: "A process of making the encrypted text readable again.",
    choice1: "decryption",
    choice2: "encryption",
    choice3: "network security",
    choice4: "information hiding",
    answer: "1",
},
{
    question: "	A small program that changes the way a computer operates.",
    choice1: "worm",
    choice2: "trojan",
    choice3: "bomb",
    choice4: "virus",
    answer: "4",
},
{
    question: "An asymmetric-key (or public-key) cipher uses",
    choice1: "1 key",
    choice2: "2 key",
    choice3: "3 key",
    choice4: "4 key",
    answer: "2",
}];