let MCQS = [{
    question: "Which of the following mentioned standard Probability density functions is applicable to discrete Random Variables?",
    choice1: "Gaussian Distribution",
    choice2: "Poisson Distribution",
    choice3: "Rayleigh Distribution",
    choice4: "Exponential Distribution",
    answer: "2",
},
{
    question: "What is the area under a conditional Cumulative density function?",
    choice1: "0",
    choice2: "Infinity",
    choice3: "1",
    choice4: "Changes with CDF",
    answer: "3",
},
{
    question: "When do the conditional density functions get converted into the marginally density functions?",
    choice1: "Only if random variables exhibit statistical dependency",
    choice2: "Only if random variables exhibit statistical independency",
    choice3: "Only if random variables exhibit deviation from its mean value",
    choice4: "If random variables do not exhibit deviation from its mean value",
    answer: "2",
},
{
    question: "Mutually Exclusive events ___________",
    choice1: "Contain all sample points",
    choice2: "Contain all common sample points",
    choice3: "Does not contain any sample point",
    choice4: "Does not contain any common sample point",
    answer: "4",
},
{
    question: "What would be the probability of an event ‘G’ if H denotes its complement, according to the axioms of probability?",
    choice1: "P (G) = 1 / P (H)",
    choice2: "P (G) = 1 - P (H)",
    choice3: "P (G) = 1 + P (H)",
    choice4: "P (G) = P (H)",
    answer: "2",
},
{
    question: "A variable that can assume any value between two given points is called ___________",
    choice1: "Continuous random variable",
    choice2: "Discrete random variable",
    choice3: "Irregular random variable",
    choice4: "Uncertain random variable",
    answer: "1",
},
{
    question: "If a variable can certain integer values between two given points is called ___________",
    choice1: "Continuous random variable",
    choice2: "Discrete random variable",
    choice3: "Irregular random variable",
    choice4: "Uncertain random variable",
    answer: "2",
}, {
    question: "The expected value of a discrete random variable ‘x’ is given by",
    choice1: "P(x)",
    choice2: "∑ P(x)",
    choice3: "∑ X P(x)",
    choice4: "1",
    answer: "3",
},
{
    question: "If ‘X’ is a continuous random variable, then the expected value is given by _",
    choice1: "P(x)",
    choice2: "∑ x P(x)",
    choice3: "∫ X P(X)",
    choice4: "No value such as expected value",
    answer: "3",
},
{
    question: "If E(x) = 2 and E(z) = 4, then E(z - x) =?",
    choice1: "2",
    choice2: "6",
    choice3: "0",
    choice4: "Insufficient data",
    answer: "1",
}];