let MCQS = [{
    question: "What is the full form of DBMS?",
    choice1: "Data of Binary Management System",
    choice2: "Database Management System",
    choice3: "Database Management Service",
    choice4: "Data Backup Management System",
    answer: "2",
},
{
    question: "What is a database?",
    choice1: "Organized collection of information that cannot be accessed, updated, and managed",
    choice2: "Collection of data or information without organizing",
    choice3: "Organized collection of data or information that can be accessed, updated, and managed",
    choice4: "Organized collection of data that cannot be updated",
    answer: "3",
},
{
    question: "What is DBMS?",
    choice1: "DBMS is a collection of queries",
    choice2: "DBMS is a high-level language",
    choice3: "DBMS is a programming language",
    choice4: "DBMS stores, modifies and retrieves data",
    answer: "4",
},
{
    question: "Which type of data can be stored in the database?",
    choice1: "Image oriented data",
    choice2: "Text, files containing data",
    choice3: "Data in the form of audio or video",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "In which of the following formats data is stored in the database management system?",
    choice1: "Image",
    choice2: "Text",
    choice3: "Table",
    choice4: "Graph",
    answer: "3",
},
{
    question: "Which of the following is not a type of database?",
    choice1: "Hierarchical",
    choice2: "Network",
    choice3: "Distributed",
    choice4: "Decentralized",
    answer: "4",
},
{
    question: "Which of the following is not an example of DBMS?",
    choice1: "Minimum Duplication and Redundancy of Data",
    choice2: "High Level of Security",
    choice3: "Single-user Access only",
    choice4: "Support ACID Property",
    answer: "3",
}, {
    question: "Which of the following is a feature of the database?",
    choice1: "No-backup for the data stored",
    choice2: "User interface provided",
    choice3: "Lack of Authentication",
    choice4: "Store data in multiple locations",
    answer: "2",
},
{
    question: "Which of the following is not a function of the database?",
    choice1: "Managing stored data",
    choice2: "Manipulating data",
    choice3: "Security for stored data",
    choice4: "Analysing code",
    answer: "4",
},
{
    question: "Which of the following is a function of the DBMS?",
    choice1: "Storing data",
    choice2: "Providing multi-users access control",
    choice3: "Data Integrity",
    choice4: "All of the above",
    answer: "4",
}];