let MCQS = [{
    question: "What is the main function of the command interpreter?",
    choice1: "to provide the interface between the API and application program",
    choice2: "to handle the files in the operating system",
    choice3: "to get and execute the next user-specified command",
    choice4: "none of the mentioned",
    answer: "3",
},
{
    question: " In Operating Systems, which of the following is/are CPU scheduling algorithms?",
    choice1: "Priority",
    choice2: "Round Robin",
    choice3: "Shortest Job First",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "To access the services of the operating system, the interface is provided by the ___________",
    choice1: "Library",
    choice2: "System calls",
    choice3: "Assembly instructions",
    choice4: "API",
    answer: "2",
},
{
    question: " CPU scheduling is the basis of ___________",
    choice1: "multiprogramming operating systems",
    choice2: "larger memory sized systems",
    choice3: "multiprocessor systems",
    choice4: " none of the mentioned",
    answer: "1",
},
{
    question: "Which one of the following errors will be handle by the operating system?",
    choice1: "lack of paper in printer",
    choice2: "connection failure in the network",
    choice3: "power failure",
    choice4: "all of the mentioned",
    answer: "4",
},
{
    question: " If a process fails, most operating system write the error information to a ______",
    choice1: "new file",
    choice2: "another running process",
    choice3: "log file",
    choice4: "none of the mentioned",
    answer: "3",
},
{
    question: "Which one of the following is not a real time operating system?",
    choice1: "RTLinux",
    choice2: "Palm Os",
    choice3: "QNX",
    choice4: "VxWorks",
    answer: "b",
}, 
{
    question: "What does OS X has?",
    choice1: "monolithic kernel with modules",
    choice2: "microkernel",
    choice3: "monolithic kernel",
    choice4: "hybrid kernel",
    answer: "4",
},
{
    question: "In operating system, each process has its own ",
    choice1: "open files",
    choice2: "pending alarms, signals, and signal handlers",
    choice3: "address space and global variables",
    choice4: "all of the mentioned",
    answer: "4",
},
{
    question: "Cascading termination refers to the termination of all child processes if the parent process terminates ______",
    choice1: "Normally or abnormally",
    choice2: "Abnormally",
    choice3: "Normally",
    choice4: "None of the mentioned",
    answer: "1",
}];