let MCQS = [{
    question: "There are ______steps to solve the problem",
    choice1: "Seven",
    choice2: "Four",
    choice3: "Six",
    choice4: "Two",
    answer: "3",
},
{
    question: "_____is the first step in solving the problem",
    choice1: "Understanding the Problem",
    choice2: "Identify the Problem",
    choice3: "Evaluate the Solution",
    choice4: "one of these",
    answer: "2",
},
{
    question: "______is the last step in solving the problem",
    choice1: "Understanding the Problem",
    choice2: "Identify the Problem",
    choice3: "Evaluate the Solution",
    choice4: "one of these",
    answer: "3",
},
{
    question: " ______ solution requires reasoning built on knowledge andexperience",
    choice1: " Algorithmic Solution",
    choice2: "Heuristic Solution",
    choice3: "Random Solution",
    choice4: "None of these",
    answer: "2",
},
{
    question: "The branch of computer that deals with heuristic types ofproblem is called _________________.",
    choice1: "system software",
    choice2: "real time software",
    choice3: "artificial intelligence",
    choice4: "None of these",
    answer: "3",
},
{
    question: "The PAC stands for",
    choice1: "Program Analysis Chart",
    choice2: "Problem Algorithm Code",
    choice3: "Problem Access Code",
    choice4: "Problem Analysis Chart",
    answer: "4",
},
{
    question: "In interactivity chart the diamond indicates",
    choice1: "duplicate module",
    choice2: "loop",
    choice3: "decision",
    choice4: "no special meaning",
    answer: "2",
}, {
    question: "The main measure for efficiency algorithm are",
    choice1: "Processor and Memory",
    choice2: "Complexity and Capacity",
    choice3: "Data and Space",
    choice4: "Time and space",
    answer: "4",
},
{
    question: "Examples of O(1) algorithms are_______",
    choice1: "Multiplying two numbers",
    choice2: "assigning some value to a variable",
    choice3: "displaying some integer on console",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "Examples of O(n2) algorithms are_______",
    choice1: "Adding of two Matrices",
    choice2: "Initializing all elements of matrix by zero",
    choice3: "Both",
    choice4: "None",
    answer: "3",
}];