let MCQS = [{
    question: "Which of the following is a stage of compiler design?",
    choice1: "Semantic analysis",
    choice2: "Intermediate code generator",
    choice3: "Code generator",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: " What is the use of a symbol table in compiler design?",
    choice1: "Finding name’s scope",
    choice2: "Type checking",
    choice3: "Keeping all of the names of all entities in one place",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "Which of the following error can a compiler check?",
    choice1: "Syntax Error",
    choice2: "Logical Error",
    choice3: "Both Logical and Syntax Error",
    choice4: "Compiler cannot check errors",
    answer: "1",
},
{
    question: "A programmer, writes a program to multiply two numbers instead of dividing them by mistake, how can this error be detected?",
    choice1: "Compiler or interpreter",
    choice2: "Compiler only",
    choice3: "Interpreter only",
    choice4: "None of the mentioned",
    answer: "4",
},
{
    question: "Who is responsible for the creation of the symbol table?",
    choice1: "Assembler",
    choice2: "Compiler",
    choice3: "Interpreter",
    choice4: "All of the mentioned",
    answer: "2",
},
{
    question: "Which of the following is a definition of compiler?",
    choice1: "Acceptance of a program written in a high-level language and produces an object program",
    choice2: "Program is put into memory and executes it",
    choice3: "Translation of assembly language into machine language",
    choice4: "None of the mentioned",
    answer: "1",
},
{
    question: "Which of the following phase of the compiler is Syntax Analysis?",
    choice1: "econd",
    choice2: "Third",
    choice3: "First",
    choice4: "All of mentioned",
    answer: "1",
}, {
    question: " Which of the following concept of FSA is used in the compiler?",
    choice1: "Code optimization",
    choice2: "Code generation",
    choice3: "Lexical analysis",
    choice4: "Parser",
    answer: "3",
},
{
    question: "What is CFG?",
    choice1: "Regular Expression",
    choice2: "Compiler",
    choice3: "Language expression",
    choice4: "All of the mentioned",
    answer: "2",
},
{
    question: "Which of the following is correct regarding an optimizer Compiler?",
    choice1: "Optimize the code",
    choice2: "Is optimized to occupy less space",
    choice3: "Both of the mentioned",
    choice4: "None of the mentioned",
    answer: "4",
}];