let MCQS = [{
    question: "A collection of hyperlinked documents on the internet forms the ?.?",
    choice1: "World Wide Web (WWW)",
    choice2: "E-mail system",
    choice3: "Mailing list",
    choice4: "Hypertext markup language",
    answer: "1",
},
{
    question: "The location of a resource on the internet is given by its?",
    choice1: "Protocol",
    choice2: "URL",
    choice3: "Email address",
    choice4: "ICQ",
    answer: "2",
},
{
    question: "The term HTTP stands for?",
    choice1: "Hyper terminal tracing program",
    choice2: "Hypertext tracing protocol",
    choice3: "Hypertext transfer protocol",
    choice4: "Hypertext transfer program",
    answer: "3",
},
{
    question: "A proxy server is used as the computer?",
    choice1: "with external access",
    choice2: "acting as a backup",
    choice3: "performing file handling",
    choice4: "accessing user permissions",
    answer: "1",
},
{
    question: "Which one of the following would breach the integrity of a system?",
    choice1: "Looking the room to prevent theft",
    choice2: "Full access rights for all users",
    choice3: "Fitting the system with an anti-theft device",
    choice4: "Protecting the device against willful or accidental damage",
    answer: "2",
},
{
    question: "Which software prevents the external access to a system?",
    choice1: "Firewall",
    choice2: "Gateway",
    choice3: "Router",
    choice4: "Virus checker",
    answer: "1",
},
{
    question: "Which of the following best describes uploading information?",
    choice1: "Sorting data on a disk drive",
    choice2: "Sending information to a host computer",
    choice3: "Receiving information from a host computer",
    choice4: "Sorting data on a hard drive",
    answer: "2",
}, {
    question: "Which one of the following is the most common internet protocol?",
    choice1: "HTML",
    choice2: "NetBEUI",
    choice3: "TCP/IP",
    choice4: "IPX/SPX",
    answer: "3",
},
{
    question: "The term FTP stands for?",
    choice1: "File transfer program",
    choice2: "File transmission protocol",
    choice3: "File transfer protocol",
    choice4: "File transfer protection",
    answer: "3",
},
{
    question: "Which one of the following is not a network topology?",
    choice1: "Star",
    choice2: "Ring",
    choice3: "Bus",
    choice4: "Peer to Peer",
    answer: "4",
}];