let MCQS = [{
    question: "Which of the following is a subset of machine learning?",
    choice1: "Nummpy",
    choice2: "Scipy",
    choice3: "Deep learning",
    choice4: "All",
    answer: "3",
},
{
    question: "How many layers Deep learning algorithms are constructed?",
    choice1: "2",
    choice2: "3",
    choice3: "4",
    choice4: "5",
    answer: "2",
},
{
    question: "The first layer is called the?",
    choice1: "inner layer",
    choice2: "outer layer",
    choice3: "hidden layer",
    choice4: "None of the above",
    answer: "1",
},
{
    question: "RNNs stands for?",
    choice1: "Receives neural networks",
    choice2: "Report neural networks",
    choice3: "Recording neural networks",
    choice4: "Recurrent neural networks",
    answer: "4",
},
{
    question: "CNN is mostly used when there is an?",
    choice1: "structured data",
    choice2: "Unstructured data",
    choice3: "ooth",
    choice4: "none",
    answer: "2",
},
{
    question: "Which neural network has only one hidden layer between the input and output?",
    choice1: "Shallow neural network",
    choice2: "Deep neural network",
    choice3: "Feed-forward neural networks",
    choice4: "Recurrent neural networks",
    answer: "1",
},
{
    question: "Deep learning algorithms are _______ more accurate than machine learning algorithm in image classification.",
    choice1: "33%",
    choice2: "37%",
    choice3: "40%",
    choice4: "41%",
    answer: "4",
}, {
    question: "In CNN, having max pooling always decrease the parameters?",
    choice1: "True",
    choice2: "False",
    choice3: "Can be true and false",
    choice4: "Can not say",
    answer: "1",
},
{
    question: "The input image has been converted into a matrix of size 28 X 28 and a kernel/filter of size 7 X 7 with a stride of 1. What will be the size of the convoluted matrix?",
    choice1: "20X20",
    choice2: "21X21",
    choice3: "22X22",
    choice4: "25X25",
    answer: "3",
},
{
    question: "The number of nodes in the input layer is 10 and the hidden layer is 5. The maximum number of connections from the input layer to the hidden layer are",
    choice1: "50",
    choice2: "less than 50",
    choice3: "more than 50",
    choice4: "it it an arbitrary value",
    answer: "1",
}];