let MCQS = [{
    question: "What is Microprocessor?",
    choice1: "A multipurpose PLD that accepts binary data as input",
    choice2: "A multipurpose PLD that accepts an integer as input",
    choice3: "A multipurpose PLD that accepts whole numbers as input",
    choice4: "A multipurpose PLD that accepts prime numbers as input",
    answer: "1",
},
{
    question: " Which of the following is correct about 8086 microprocessor?",
    choice1: "Intel’s first x86 processor",
    choice2: "Motrola’s first x86 processor",
    choice3: "STMICROELECTRONICS’s first x86 processor",
    choice4: "NanoXplore x86 processor",
    answer: "1",
},
{
    question: "Which of the following is a type of microprocessor?",
    choice1: "CISC",
    choice2: "RISC",
    choice3: "EPIC",
    choice4: "All of the mentioned",
    answer: "4",
},
{
    question: "The microprocessor of a computer can operate on any information if it is present in ______________ only.",
    choice1: "Program Counter",
    choice2: "Flag",
    choice3: "Main Memory",
    choice4: "Secondary memory",
    answer: "3",
},
{
    question: "Which of the following technology was used by Intel to design its first 8-bit microprocessor?",
    choice1: "NMOS",
    choice2: "HMOS",
    choice3: "PMOS",
    choice4: "TTL",
    answer: "3",
},
{
    question: " Which of the following addressing method does the instruction, MOV AX,[BX] represent?",
    choice1: "register indirect addressing mode",
    choice2: "direct addressing mode",
    choice3: "register addressing mode",
    choice4: "register relative addressing mode",
    answer: "1",
},
{
    question: "What is the word length of an 8-bit microprocessor?",
    choice1: "8-bits - 64 bits",
    choice2: "4-bits - 32 bits",
    choice3: "8-bits - 16 bits",
    choice4: "8-bits - 32 bits",
    answer: "1",
}, {
    question: "In 8-bit microprocessor, how many opcodes are present?",
    choice1: "246",
    choice2: "278",
    choice3: "250",
    choice4: "256",
    answer: "1",
},
{
    question: "Which of the following is true about microprocessors?",
    choice1: "It has an internal memory",
    choice2: "It has interfacing circuits",
    choice3: "It contains ALU, CU, and registers",
    choice4: "It uses Harvard architecture",
    answer: "3",
},
{
    question: "Which of the following is not a property of TRAP interrupt in microprocessor?",
    choice1: "It is a non-maskable interrupt",
    choice2: "It is of highest priority",
    choice3: "It uses edge-triggered signal",
    choice4: "It is a vectored interrupt",
    answer: "3",
}];