let MCQS = [{
    question: "Which of the following is the first charter of Human's rights?",
    choice1: "Bill of rights",
    choice2: "Constitution of media",
    choice3: "The Cyrus cylinder",
    choice4: "None of the above",
    answer: "3",
},
{
    question: "Who played an important role in international human rights law?",
    choice1: "Economic summit",
    choice2: "World War",
    choice3: "The United Nations",
    choice4: "None of the above",
    answer: "3",
},
{
    question: "Who adopted the landmark document, the universal declaration of human rights?",
    choice1: "UNESCO",
    choice2: "UNICEF",
    choice3: "UNO",
    choice4: "None of the above",
    answer: "3",
},
{
    question: "Which article of the universal declaration of human rights tells that the right of nationality depends on one's wish?",
    choice1: "Article 10",
    choice2: "Article 20",
    choice3: "Article 30",
    choice4: "Article 15",
    answer: "4",
},
{
    question: "Who is the current chairman of the NHRC (National Human rights commission)?",
    choice1: "Justice H.L. Dattu",
    choice2: "Justice A.S. Anand",
    choice3: "Both of the above",
    choice4: "None",
    answer: "1",
},
{
    question: "What is the full form of UNHCR?",
    choice1: "United Nations high commissioner for refugees",
    choice2: "United Nations high-level committee for refugees",
    choice3: "United Nations health committee for refugees",
    choice4: "None",
    answer: "1",
},
{
    question: "NHRC consists of a chairman and -",
    choice1: "Four members",
    choice2: "Three members",
    choice3: "Two members",
    choice4: "None",
    answer: "1",
}, {
    question: "In which year have the changes been made in the NHRC (National Human Right Commission) Act?",
    choice1: "1999",
    choice2: "2000",
    choice3: "2005",
    choice4: "2006",
    answer: "4",
},
{
    question: "Article 21 of the Indian Constitution provides for -",
    choice1: "Right to subsist",
    choice2: "Right to lively and liberal life",
    choice3: "Right to die",
    choice4: "Right to lively and liberal life",
    answer: "4",
},
{
    question: "The tenure of the chairperson of NHRC (National Human Rights Commission) is -",
    choice1: "4 years or upto 68 years of age",
    choice2: "3 years or upto 69 years of age",
    choice3: "5 years or upto 70 years of age",
    choice4: "None of the above",
    answer: "3",
}];