let MCQS = [{
    question: "Which of the following is the way in which an IoT device is associated with data?",
    choice1: "Internet",
    choice2: "Cloud",
    choice3: "Automata",
    choice4: "Network",
    answer: "2",
},
{
    question: "Which of the following IoT networks has a very short range?",
    choice1: "Short Network",
    choice2: "LPWAN",
    choice3: "SigFox",
    choice4: "Short Range Wireless Network",
    answer: "4",
},
{
    question: "What is the full form of the LPWAN?",
    choice1: "Low Protocol Wide Area Network",
    choice2: "Low Power Wide Area Network",
    choice3: "Long Protocol Wide Area Network",
    choice4: "Long Power Wide Area Network",
    answer: "2",
},
{
    question: "An IoT network is a collection of ______ devices.",
    choice1: "Signal",
    choice2: "Machine to Machine",
    choice3: "Interconnected",
    choice4: "Network to Network",
    answer: "3",
},
{
    question: "Which one of the following is not an IoT device?",
    choice1: "Amazon echo voice controller",
    choice2: "Google Home",
    choice3: "Nest Smoke Alarm",
    choice4: "None of these",
    answer: "4",
},
{
    question: "What is the main purpose of WoT (Web of Things) in the IoT?",
    choice1: "Improve the usability and interoperability",
    choice2: "Reduce the security",
    choice3: "Complex the development",
    choice4: "Increase the cost",
    answer: "1",
},
{
    question: "Which of the following is not an application of IoT?",
    choice1: "Wearables",
    choice2: "Smart Grid",
    choice3: "Arduino",
    choice4: "Smart city",
    answer: "3",
}, {
    question: "What is the role of Big Data in IoT's Smart Grid architecture?",
    choice1: "Filter the data",
    choice2: "Locked the data",
    choice3: "Store data",
    choice4: "None of the these",
    answer: "3",
},
{
    question: "Which of the following layers provides end-to-end communication in IoT?",
    choice1: "Logical layer",
    choice2: "Data link layer",
    choice3: "Transport layer",
    choice4: "Session layer",
    answer: "3",
},
{
    question: "Which interface does the fingerprint sensor use?",
    choice1: "UART interface",
    choice2: "CoAP interface",
    choice3: "SPI interface",
    choice4: "I2P interface",
    answer: "1",
}];