let MCQS = [{
    question: "In C, parameters are always ",
    choice1: "Passed by value",
    choice2: "Passed by reference",
    choice3: "Non-pointer variables are passed by value and pointers are passed by reference",
    choice4: "Passed by value result",
    answer: "3",
},
{
    question: "Who is the father of C language?",
    choice1: "Steve Jobs",
    choice2: "James Gosling",
    choice3: "Dennis Ritchie",
    choice4: "Rasmus Lerdorf",
    answer: "3",
},
{
    question: "Which is valid C expression?",
    choice1: "int my_num = 100,000;",
    choice2: "int my_num = 100000;",
    choice3: "int my num = 1000;",
    choice4: "int $my_num = 10000;",
    answer: "2",
},
{
    question: "What is short int in C programming?",
    choice1: "The basic data type of C",
    choice2: "Qualifier",
    choice3: "Short is the qualifier and int is the basic data type",
    choice4: "All of the mentioned",
    answer: "3",
},
{
    question: "Which of the following declaration is not supported by C language?",
    choice1: "String str;",
    choice2: "char *str;",
    choice3: "float str = 3e2;",
    choice4: "Both “String str;” and “float str = 3e2;”",
    answer: "1",
},
{
    question: "Which of the following typecasting is accepted by C language?",
    choice1: "Widening conversions",
    choice2: "Narrowing conversions",
    choice3: "Widening & Narrowing conversions",
    choice4: "None of the mentioned",
    answer: "3",
},
{
    question: "Functions in C Language are always _________",
    choice1: "Internal",
    choice2: "External",
    choice3: "Both Internal and External",
    choice4: "External and Internal are not valid terms for functions",
    answer: "2",
}, {
    question: "Which of the following are C preprocessors?",
    choice1: "#ifdef",
    choice2: "#define",
    choice3: "#endif",
    choice4: "all of the mentioned",
    answer: "4",
},
{
    question: "The C-preprocessors are specified with _________ symbol.",
    choice1: "#",
    choice2: "$",
    choice3: "@",
    choice4: "&",
    answer: "1",
},
{
    question: "How many number of pointer (*) does C have against a pointer variable declaration?",
    choice1: "7",
    choice2: "127",
    choice3: "155",
    choice4: "NO limits",
    answer: "4",
}];