let MCQS = [{
    question: " What is Mechanics?",
    choice1: " Branch of science which deals with failure analysis",
    choice2: "Branch of science which deals with conditions of rest or motion of bodies",
    choice3: " Branch of science which deals with the study of bodies only under rest",
    choice4: " Branch of science which deals with the study of bodies only under motion",
    answer: "2",
},
{
    question: "Which of the following is the basic law for mechanics?",
    choice1: "Newton’s law of viscosity",
    choice2: "Parallelogram law",
    choice3: "Newton’s laws of motion",
    choice4: "Hooke’s law",
    answer: "3",
},
{
    question: "Which of the following is the SI unit of force?",
    choice1: "Kg m",
    choice2: "Kg m2",
    choice3: "Kg m2/s",
    choice4: " Kg m/s2 ",
    answer: "4",
},
{
    question: "Which of the following statements describes the resultant of two forces?",
    choice1: "Force that maintains the system in equilibrium",
    choice2: "Force that has the highest magnitude in the system",
    choice3: "Force that has the same effect as the two forces",
    choice4: "Force that has the same effect as one force",
    answer: "3",
},
{
    question: "The point of application where the total weight can be expected to be concentrated if the gravitational force is dispersed across the volume of the body is called ______",
    choice1: "The surface of the body",
    choice2: "The centroid of the body",
    choice3: "Center of gravity of the body",
    choice4: "Moment of inertia",
    answer: "3",
},
{
    question: "When there is no relative force between touching surfaces, which of the following force is developed?",
    choice1: "Dry friction",
    choice2: "Dynamic friction",
    choice3: "Fluid friction",
    choice4: "Static friction",
    answer: "4",
},
{
    question: "What is the relationship between each force, if three concurrent forces acting on a body according to Lami’s theorem?",
    choice1: "Directly proportional to the sine of the angle between the other two forces",
    choice2: "Inversely proportional to the cosine of the angle between the other two forces",
    choice3: "Directly proportional to the cosine of the angle between the other two forces",
    choice4: "Inversely proportional to the sine of the angle between the other two forces",
    answer: "1",
}, {
    question: "The moment is the cross product of which of the following two vectors/scalars?",
    choice1: "Force and Radius scalars",
    choice2: "Radius and Force scalars",
    choice3: "Force and Radius vectors",
    choice4: "Radius and Force vectors",
    answer: "4",
},
{
    question: "The change in the moment is equal to which of the following?",
    choice1: "Rotational moment",
    choice2: "Bending moment",
    choice3: "Total weight",
    choice4: "Area under the shear diagram",
    answer: "4",
},
{
    question: " In the free body diagrams, the normal forces acting on the belt are in which of the following direction for calculating the equilibrium equations?",
    choice1: "Horizontally Left",
    choice2: "Horizontally Right",
    choice3: "Vertically Upward",
    choice4: "Vertically Downward",
    answer: "4",
}];