let MCQS = [{
    question: "What is the name of the conceptual framework in which the research is carried out?",
    choice1: "Research hypothesis",
    choice2: "Synopsis of Research",
    choice3: "Research paradigm",
    choice4: "Research design",
    answer: "4",
},
{
    question: "What is the main role of research in education?",
    choice1: "To upsurge one's social status.",
    choice2: "To increase one's job prospects.",
    choice3: "To augment one's personal growth.",
    choice4: "To help an applicant in becoming a renowned educationalist.",
    answer: "4",
},
{
    question: "Which of the following features are considered as critical in qualitative research?",
    choice1: "Collecting data with the help of standardized research tools",
    choice2: "Design sampling with probability sample techniques.",
    choice3: "Collecting data with bottom-up empirical evidence",
    choice4: "Gathering data with top-down schematic evidence.",
    answer: "3",
},
{
    question: "How is random sampling helpful?",
    choice1: "Reasonably accurate",
    choice2: "An economical method of data collection",
    choice3: "Free from personal biases",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "Tippit table refers to as _________",
    choice1: "Table of random digits",
    choice2: "The table used in sampling methods",
    choice3: "The table used in statistical investigations",
    choice4: "All of the above",
    answer: "4",
},
{
    question: "In order to pursue the research, which of the following is priorly required?",
    choice1: "Developing a research design",
    choice2: "Formulating a research question",
    choice3: "Deciding about the data analysis procedure",
    choice4: "Formulating a research hypothesis",
    answer: "2",
},
{
    question: "The format of thesis writing is the same as in",
    choice1: "Writing of Seminar representation",
    choice2: "Preparation of research paper/article",
    choice3: "A research dissertation",
    choice4: "Presenting a workshop/conference paper",
    answer: "3",
}, {
    question: "Which one among the following statements is false in the context of participatory research?",
    choice1: "It recognizes knowledge as power",
    choice2: "It is a collective process of inquiry",
    choice3: "It emphasizes people as experts",
    choice4: "Its sole purpose is the production of knowledge",
    answer: "4",
},
{
    question: "What does the longitudinal research approach actually deal with?",
    choice1: "Long-term research",
    choice2: "Short-term research",
    choice3: "Horizontal research",
    choice4: "None of the above",
    answer: "1",
},
{
    question: "What do you understand by the term Anusandhan?",
    choice1: "Goal-oriented",
    choice2: "Following an aim",
    choice3: "Attaining an aim",
    choice4: "Praying to achieve an aim",
    answer: "2",
}];