let MCQS = [{
    question: "Which of the following is linear data structure? ",
    choice1: "Trees",
    choice2: "Graphs",
    choice3: "Arrays",
    choice4: "None",
    answer: "3",
},
{
    question: "Which of the following is non-linear data structure? ",
    choice1: "Arrays",
    choice2: "Linked List",
    choice3: "Stacks",
    choice4: "None",
    answer: "4",
},
{
    question: "Which notation is used to find the complexity of an algorithm? ",
    choice1: "Asymptotic Notation",
    choice2: "Big oh Notation",
    choice3: "Omega Notation",
    choice4: "none",
    answer: "1",
},
{
    question: "Data Structure that allows fast search within an ordered sequence of elements is called?",
    choice1: "Skip list",
    choice2: "list",
    choice3: "Array",
    choice4: "None",
    answer: "1",
},
{
    question: "User defined data type is also called?",
    choice1: "Primitive",
    choice2: "Non Primitive",
    choice3: "Identifier",
    choice4: "None",
    answer: "2",
},
{
    question: "Stack is based on which principle",
    choice1: "FIFO",
    choice2: "Push",
    choice3: "LIFO",
    choice4: "None",
    answer: "3",
},
{
    question: "When the data structure is combined with its operation then, data structure is known as ",
    choice1: "Topology",
    choice2: "Data Structure",
    choice3: "Abstract Data Type",
    choice4: "None of these",
    answer: "3",
}, {
    question: " Function is to specify the data type",
    choice1: "typedef",
    choice2: "arr",
    choice3: "id",
    choice4: "None of these",
    answer: "1",
},
{
    question: "Omega Notation is also known as ",
    choice1: "Upper Bound",
    choice2: "Lower Bound",
    choice3: "Minimun Bound",
    choice4: "None of these",
    answer: "1",
},
{
    question: "A function which calls itself is called ",
    choice1: "Recursion",
    choice2: "Iteration",
    choice3: "Algorithm",
    choice4: "None of these",
    answer: "1",
}];