let MCQS = [{
    question: "Which of the following option leads to the portability and security of Java?",
    choice1: "Bytecode is executed by JVM",
    choice2: "The applet makes the Java code secure and portable",
    choice3: "Use of exception handling",
    choice4: "Dynamic binding between objects",
    answer: "1",
},
{
    question: "Which of the following is not a Java features?",
    choice1: "Dynamic",
    choice2: "Architecture Neutral",
    choice3: "Use of pointers",
    choice4: "Object-oriented",
    answer: "3",
},
{
    question: "The \u0021 article referred to as a",
    choice1: "Unicode escape sequence",
    choice2: "Octal escape",
    choice3: "Hexadecimal",
    choice4: "Line feed",
    answer: "1",
},
{
    question: "_____ is used to find and fix bugs in the Java programs.",
    choice1: "JVM",
    choice2: "JRE",
    choice3: "JDK",
    choice4: "JDB",
    answer: "4",
},
{
    question: "Which of the following is a valid declaration of a char?",
    choice1: "char ch = uteaa;",
    choice2: "char ca = 'tea';",
    choice3: "char cr = \u0223;",
    choice4: "char cc = '\itea';",
    answer: "1",
},
{
    question: "What is the return type of the hashCode() method in the Object class?",
    choice1: "object",
    choice2: "int",
    choice3: "long",
    choice4: "void",
    answer: "2",
},
{
    question: " What does the expression float a = 35 / 0 return?",
    choice1: "0",
    choice2: "Not a Number",
    choice3: "Infinity",
    choice4: "Run time exception",
    answer: "3",
}, {
    question: "Which of the following for loop declaration is not valid?",
    choice1: "for ( int i = 99; i >= 0; i / 9 )",
    choice2: "for ( int i = 7; i <= 77; i += 7 )",
    choice3: "for ( int i = 20; i >= 2; - -i )",
    choice4: "for ( int i = 2; i <= 20; i = 2* i )",
    answer: "1",
},
{
    question: "Which of the following is true about the anonymous inner class?",
    choice1: "It has only methods",
    choice2: "Objects can't be created",
    choice3: "It has a fixed class name",
    choice4: "It has no class name",
    answer: "4",
},
{
    question: "Which package contains the Random class?",
    choice1: "java.util package",
    choice2: "java.lang package",
    choice3: "java.awt package",
    choice4: "java.io package",
    answer: "1",
}];